#!/usr/bin/env python3
"""
Call LLM to produce entity-mapping (replacements config) from prompt JSONs.

Reads prompt files generated by ``db_translate_prompt.py``, translates
schemas and content in parallel, and writes a unified replacements config
for ``db_translate_sqlite.py``.
"""

import argparse
import json
import os
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed

from tqdm import tqdm

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from utils import get_llm_client, parse_llm_json


def ask_llm(client, prompt, model="qwen-plus"):
    try:
        resp = client.chat.completions.create(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.0,
        )
        return resp.choices[0].message.content.strip()
    except Exception as e:
        print(f"Error calling LLM: {e}")
        return None


def process_single_schema(client, item, model="qwen-plus"):
    """Translate table and column names for one database."""
    db_id = item["db_id"]
    raw = ask_llm(client, item["prompt"], model=model)
    translated = parse_llm_json(raw, f"Schema:{db_id}")
    if not translated:
        return None

    tables = list(zip(item["table_names"], translated.get("table_names", [])))
    columns = []
    for old_info, new_info in zip(item["column_names"], translated.get("column_names", [])):
        table_idx, old_col = old_info
        if table_idx == -1:
            continue
        table_name = item["table_names"][table_idx]
        columns.append((table_name, old_col, new_info[1]))

    return {"db_id": db_id, "tables": tables, "columns": columns}


def process_single_content(client, item, model="qwen-plus"):
    """Translate values for a PK/FK column group."""
    db_id = item["db_id"]
    tables_columns = item["tables_columns"]
    raw = ask_llm(client, item["prompt"], model=model)

    log_info = f"{tables_columns[0][0]}.{tables_columns[0][1]} (Group of {len(tables_columns)})"
    translated_map = parse_llm_json(raw, log_info)
    if not translated_map:
        return None

    values = []
    for table_name, column_name in tables_columns:
        for old_val, new_val in translated_map.items():
            if str(old_val) == str(new_val):
                continue
            values.append((table_name, column_name, old_val, new_val))

    return {"db_id": db_id, "values": values}


def save_config(final_config, path):
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(final_config, f, ensure_ascii=False, indent=2)


def main():
    parser = argparse.ArgumentParser(description="Call LLM to produce replacements config.")
    parser.add_argument("--prompts-dir", required=True, help="Directory of prompt JSON files")
    parser.add_argument("--output-config", default="../../intermediate_data/replacement_configs/replacements_config.json",
                        help="Output replacements config JSON")
    parser.add_argument("--model", default="qwen-plus", help="LLM model name")
    parser.add_argument("--workers", type=int, default=10, help="Max concurrent LLM requests")
    parser.add_argument("--api-key", default=None, help="API key (or OPENAI_API_KEY)")
    parser.add_argument("--api-base", default=None, help="API base URL (or OPENAI_BASE_URL)")
    args = parser.parse_args()

    client = get_llm_client(api_key=args.api_key, base_url=args.api_base)

    schema_prompts, content_prompts = [], []
    for f_name in os.listdir(args.prompts_dir):
        if not f_name.endswith(".json"):
            continue
        with open(os.path.join(args.prompts_dir, f_name), "r", encoding="utf-8") as f:
            data = json.load(f)
        for p in data:
            (schema_prompts if p["type"] == "schema" else content_prompts).append(p)

    final_config = {}

    # Phase 1: schemas
    print(f"Translating {len(schema_prompts)} schemas...")
    with ThreadPoolExecutor(max_workers=args.workers) as executor:
        futures = {
            executor.submit(process_single_schema, client, p, args.model): p["db_id"]
            for p in schema_prompts
        }
        for future in tqdm(as_completed(futures), total=len(futures)):
            res = future.result()
            if res:
                final_config[res["db_id"]] = {
                    "tables": res["tables"],
                    "columns": res["columns"],
                    "values": [],
                }

    save_config(final_config, args.output_config)
    print(f"Saved {len(final_config)} schemas")

    # Phase 2: content
    print(f"Translating {len(content_prompts)} content batches...")
    with ThreadPoolExecutor(max_workers=args.workers) as executor:
        futures = {
            executor.submit(process_single_content, client, p, args.model): p["db_id"]
            for p in content_prompts
        }
        for future in tqdm(as_completed(futures), total=len(futures)):
            res = future.result()
            if res and res["db_id"] in final_config:
                final_config[res["db_id"]]["values"].extend(res["values"])

    save_config(final_config, args.output_config)
    print(f"Done! Config saved to {args.output_config}")


if __name__ == "__main__":
    main()
